welcome: "Welcome to Calculator!"
name: "What's your name?"
no_name: "Since you didn't enter a name, we'll just call you 'Bob'. Hi, Bob!"
intro: "This calculator performs operations on two numbers."
num01: "Please enter your first integer."
num01_error: "Whoops! That's not a valid number. Please enter your first integer again."
operator_prompt: 
  "Please choose a mathemathical operator.
    To add, enter '1'.
    To subtract, enter '2'.
    To divide, enter '3'.
    To multiply, enter '4'."
operator_error: "Whoops! That is not a valid choice."
num02: "Please enter your second integer."
num02_error: "Whoops! That is not a valid number. Please enter your second integer again."
result: "The result is: "
repeat: "Would you like to use Calculator again? (y/n)"
bye: "Thank you for using Calculator. Good-bye!"
